#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#Rodar o php stan

./vendor/bin/phpstan 
if [ $? -ne 0 ]; then
    echo "Deu erro no phpstan! verifique e arrume";
    exit 1;
fi;




#Formatar cada arquvi usando o pint

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM |  grep ".php\{0,1\}$") || true

 for FILE in STAGED_FILES 

 do
    ./vendor/bin/pint "${FILE}" 

    git add "{$FILE}"
      
done;

exit 0;