#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o php stan
./vendor/bin/phpstan analyse

if [ $? -ne 0 ]; then
    echo "Erro encontrado no PHPStan! Verifique e corrija."
    exit 1
fi


#Rodar teste paralelos;

php artisan test --parallel

if [ $? -ne 0 ]; then 
    echo "Deu erro nos seus testes"
    exit 1
fi


# Formatar cada arquivo usando o pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES; 
do
    ./vendor/bin/pint "$FILE"
    git add "$FILE"
done

exit 0
